[project]
name = "enhancing-long-context-utilization-in-llms-biu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "transformers>=4.57.1",
    "xopen>=2.0.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
